### ISSUE TITLE
The toolbar in the data view is broken

### ISSUE THREAD

**Issue by tateren** [rmehri01/onenord-jetbrains#10] opened 2023-08-23 06:48 UTC
Thanks for the great theme!

It seems that the toolbar rendering is broken when a color is set in the database.
This does not occur when colors are not set in the database or when another theme is used.

![2023-08-23 14_21_56-Window](https://github.com/rmehri01/onenord-jetbrains/assets/8104255/5f7ab528-4293-4ed1-a943-06fd8531fb0c)

Product and version: PhpStorm 2023.2
Operationg system: Windows 11
Plugin version: 0.0.6

**Comment by rmehri01** [comment] 2023-08-23 16:34
Hey there, thanks I'm glad you like the theme! 😄

Hmm, it seems like a few toolbars overlapping, which shouldn't be controlled by the plugin but its strange that it only happens with this theme. 

I can't seem to reproduce it on my mac, though I'm not that familiar with using the data tools. I basically just loaded up a sample SQLite database and right clicked on one of the tables, then did `Tools` > `Set Color` and got this result:

<img width="1582" alt="Screenshot 2023-08-23 at 10 27 12 AM" src="https://github.com/rmehri01/onenord-jetbrains/assets/52933714/7cdc7c7e-c34d-416a-851a-0c018d71fcd9">

Do you have any other details on how to reproduce it?

**Comment by tateren** [comment] 2023-08-25 00:55
When hovering the mouse over the toolbar, the drawing is corrupted.
It seems that some colors reproduce and some do not.

![20230825](https://github.com/rmehri01/onenord-jetbrains/assets/8104255/6a9fcb89-1d4b-4b9c-b3cb-03aa23492ed2)

This problem occurred even when I did Restore Default Setting and minimized the configuration.
This also occurs with another product (DataGrip).

**Comment by rmehri01** [comment] 2023-08-25 00:59
Ah okay interesting, I can reproduce something similar now when using different colors thanks, I'll look into it!

**Comment by rmehri01** [comment] 2023-08-28 17:04
So I believe the issue is that these colors are taken from `FileColors`, which right now have alpha values. These seem to work in other places in the editor but not in this toolbar and I've been able to reproduce this issue in a few other themes including Nord and Gradianto that also have alpha values in the `FileColors`.

**Comment by rmehri01** [comment] 2023-09-02 17:51
I don't seem to be getting a response, so I'm just going to make the `FileColors` not have alpha values in them.

**Comment by rmehri01** [comment] 2023-09-02 18:57
Should be fixed in the next release! 😄

**Comment by tateren** [comment] 2023-09-04 01:23
Thanks a lot!

**Closed** 2023-09-04 16:01 UTC
